# Generated by Django 4.2.6 on 2023-11-27 09:18

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=200)),
                ('due', models.DateTimeField(default=tasks.models.default_due)),
            ],
        ),
    ]
